services:
  - type: web
    name: digital-e-panchayat-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    repo: https://github.com/Chiranjeevi005/-Digital-E-Gram-Panchayat-
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3002

  # Frontend service
  - type: web
    name: digital-e-panchayat-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    repo: https://github.com/Chiranjeevi005/-Digital-E-Gram-Panchayat-
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000